
package fr.ensma.lisi.notebookwebservicefromwsdl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6b21 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Notebook", targetNamespace = "http://notebookwebservice.lisi.ensma.fr/", wsdlLocation = "file:/H:/work/web%20service/jaxws_examples/eclipse3.5/NotebookWebServiceFromWSDL/src/wsdl/notebook.wsdl")
public class Notebook_Service
    extends Service
{

    private final static URL NOTEBOOK_WSDL_LOCATION;
    private final static WebServiceException NOTEBOOK_EXCEPTION;
    private final static QName NOTEBOOK_QNAME = new QName("http://notebookwebservice.lisi.ensma.fr/", "Notebook");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/H:/work/web%20service/jaxws_examples/eclipse3.5/NotebookWebServiceFromWSDL/src/wsdl/notebook.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        NOTEBOOK_WSDL_LOCATION = url;
        NOTEBOOK_EXCEPTION = e;
    }

    public Notebook_Service() {
        super(__getWsdlLocation(), NOTEBOOK_QNAME);
    }

    public Notebook_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), NOTEBOOK_QNAME, features);
    }

    public Notebook_Service(URL wsdlLocation) {
        super(wsdlLocation, NOTEBOOK_QNAME);
    }

    public Notebook_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, NOTEBOOK_QNAME, features);
    }

    public Notebook_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Notebook_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Notebook
     */
    @WebEndpoint(name = "NoteBookPort")
    public Notebook getNoteBookPort() {
        return super.getPort(new QName("http://notebookwebservice.lisi.ensma.fr/", "NoteBookPort"), Notebook.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Notebook
     */
    @WebEndpoint(name = "NoteBookPort")
    public Notebook getNoteBookPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://notebookwebservice.lisi.ensma.fr/", "NoteBookPort"), Notebook.class, features);
    }

    private static URL __getWsdlLocation() {
        if (NOTEBOOK_EXCEPTION!= null) {
            throw NOTEBOOK_EXCEPTION;
        }
        return NOTEBOOK_WSDL_LOCATION;
    }

}
